[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]"
]
build-backend = "setuptools.build_meta"

# pyproject.toml
[tool.setuptools_scm]
"write_to" = "src/zhinst/deviceutils/_version.py"
"local_scheme" = "no-local-version"
